services:
  api:
    build:
      context: ./api
    image: mach-mlops-api:latest
    container_name: mach-mlops-api
    ports:
      - "18180:8080"
    restart: always
  swagger:
    build:
      context: ./swagger
    image: mach-mlops-swagger:latest
    container_name: mach-mlops-swagger
    ports:
      - "18181:80"
    restart: always